name: lua
description: Lua language utilities in Dart.
version: 0.1.0
repository: https://github.com/agilord/lua

environment:
  sdk: ^3.1.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
