name: lua
description: Lua language utilities in Dart.
version: 0.1.1
repository: https://github.com/agilord/lua

environment:
  sdk: ^3.1.0

dependencies:
  collection: ^1.18.0
  petitparser: ^6.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
